name: Build and Release

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      version:
        description: 'wireguard-go version'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Get Version Number
        run: |
          if [[ -n "${{ github.event.inputs.version }}" ]]; then
            WGGO_VERSION=${{ github.event.inputs.version }}
          else
            WGGO_VERSION=$(curl -fsSL https://api.github.com/repos/WireGuard/wireguard-go/tags | grep 'name' | head -1 | cut -d'"' -f4)
          fi
          echo "WGGO_VERSION=${WGGO_VERSION}" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build
        run: |
          env GOOS=linux GOARCH=x86 go build -o build/x86/discord-bot main.go
          env GOOS=linux GOARCH=arm GOARM=7 go build -o build/arm7/discord-bot main.go
          env GOOS=linux GOARCH=arm64 go build -o build/arm64/discord-bot main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: wireguard-go-${{ env.WGGO_VERSION }}
          path: build

      - name: Upload to Release
        if: github.event.inputs.version == ''
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/*
          tag: ${{ env.WGGO_VERSION }}
          overwrite: true
          file_glob: true
          prerelease: true
