name: Build Bots

on:
 push:

jobs:
 build-bots:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - name: build executables
     run: |
       go build -o build/x86/discord-bot main.go
       env GOOS=linux GOARCH=arm GOARM=7 go build -o build/arm7/discord.bot main.go
       env GOOS=linux GOARCH=arm64 go build -o build/arm64/discord.bot main.go
   - name: commit files
     run: |
        git config --local user.name "mkasun"
        git add ./build
        git commit -m "updating executables"
   - name: Push changes
     uses: ad-m/github-push-action@master
     with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
