name: Release

on:
    pull_request:
        branches:
            - 'main'

jobs:
    release:
        name: "Pre Release"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Upload Release Asset
              uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  automatice_release_tag: "latest"
                  prerelease: true
                  title: "Development Build"
                  files: build/*/*
