name: Release

on:
    pull_request:
        branches:
            - 'main'

jobs:
    release:
        name: "Pre Release"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Create Tag
              id: tag
              uses: actions/github-script@v7
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN }}
                  script: |
                      github.git.createRef({
                          owner: context.repo.owner,
                          repo: context.repo.repo,
                          ref: "refs/tag/tagname",
                          sha: context.sha
                      })
            - name: Upload Release Asset
              uses: marvinpinto/action-automatic-releases@latest
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  automatic_release_tag: ${{ steps.tag.outputs.result }}
                  prerelease: true
                  title: "Development Build"
                  files: build/*/*
                  draft: true
